OL4RENT/Controllers/WishController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ol4RentAPI.Model;
using Ol4RentAPI.Facades;
using Ol4RentAPI.DTO;

namespace OL4RENT.Controllers
{
    public class WishController : Controller
    {
        private ModelContainer db = new ModelContainer();

        //
        // GET: /Wish/

        public ActionResult Index()
        {
            return View(db.EspecificacionesBienes.ToList());
        }

        //
        // GET: /Wish/Details/5

        public ActionResult Details(int id = 0)
        {
            EspecificacionBienDTO wish = ServiceFacadeFactory.Instance.EspecificacionBienFacade.Obtener(id);
            if (wish == null)
            {
                return HttpNotFound();
            }
            return View(wish);
        }

        //
        // GET: /Wish/Create

        public ActionResult Create()
        {
             if (Session["sitio"] == null)
            {
                ViewBag.Click = false;
                return RedirectToAction("Index", "Home");
            }
            else
             {
                ViewBag.Click = false;
                ArmarListadoCaracteristicas();
                return View(new EspecificacionBienAltaDTO());
            }            
        }

        private List<CaracteristicaEdicionDTO> ObtenerListadoCaracteristicas()
        {
            if (Session["sitio"] != null)
            {
                SitioListadoDTO sitio = Session["sitio"] as SitioListadoDTO;
                List<CaracteristicaEdicionDTO> caracteristicas = ServiceFacadeFactory.Instance.SitioFacade.ObtenerCaracteristicasParaEdicion(sitio.Id);
                return caracteristicas;
            }
            else
            {
                return new List<CaracteristicaEdicionDTO>();
            }
        }

        private void ArmarListadoCaracteristicas()
        {
            List<CaracteristicaEdicionDTO> caracteristicas = ObtenerListadoCaracteristicas();
            ViewBag.Caracteristicas = caracteristicas;
        }

        //
        // POST: /Wish/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EspecificacionBienAltaDTO wishDTO, bool click)
        {
            ViewBag.Click = click;
            if (wishDTO.ValoresCaracteristicas == null)
            {
                wishDTO.ValoresCaracteristicas = new List<ValorCaracteristicaAltaDTO>();
            }
            List<CaracteristicaEdicionDTO> caracteristicas = ObtenerListadoCaracteristicas();
            foreach (CaracteristicaEdicionDTO caracteristica in caracteristicas)
            {
                string id = "car-" + caracteristica.Id.ToString();
                if (Request[id] == null)
                {
                    if (caracteristica.Tipo == TipoDato.BOOLEANO)
                    {
                        wishDTO.ValoresCaracteristicas.Add(new ValorCaracteristicaAltaDTO() { Valor = "false", IdCaracteristica = caracteristica.Id });
                    }
                    else
                    {
                        wishDTO.ValoresCaracteristicas.Add(new ValorCaracteristicaAltaDTO() { Valor = "", IdCaracteristica = caracteristica.Id });
                    }
                }
                else
                {
                    if (caracteristica.Tipo == TipoDato.BOOLEANO)
                    {
                        bool boolean = Request[id].ToString() != "false";
                        wishDTO.ValoresCaracteristicas.Add(new ValorCaracteristicaAltaDTO() { Valor = boolean.ToString(), IdCaracteristica = caracteristica.Id });
                    }
                    else
                    {
                        wishDTO.ValoresCaracteristicas.Add(new ValorCaracteristicaAltaDTO() { Valor = Request[id], IdCaracteristica = caracteristica.Id });
                    }
                }
            }
            wishDTO.Usuario = User.Identity.Name;
            SitioListadoDTO sitio = Session["sitio"] as SitioListadoDTO;
            wishDTO.TipoBien = ServiceFacadeFactory.Instance.SitioFacade.ObtenerIdTipoBien(sitio.Id);
            if (ViewBag.Click)
            {
                if ((ServiceFacadeFactory.Instance.EspecificacionBienFacade.Crear(wishDTO)))
                {
                    return RedirectToAction("Wishlist");
                }
                else
                {
                    ArmarListadoCaracteristicas();
                    return View(wishDTO);
                }
            }
            else
            {
                ModelState.AddModelError("Rango", "Debe seleccionar un punto del mapa");
                ArmarListadoCaracteristicas();
                return View(wishDTO);
            }
        }

        //
        // GET: /Wish/Edit/5

        public ActionResult Edit(int id = 0)
        {
            EspecificacionBienDTO especificacionbien = ServiceFacadeFactory.Instance.EspecificacionBienFacade.Obtener(id);
            if (especificacionbien == null)
            {
                return HttpNotFound();
            }
            return View(especificacionbien);
        }

        //
        // POST: /Wish/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EspecificacionBienDTO wishDTO)
        {
            if (wishDTO.ValoresCaracteristicas == null)
            {
                wishDTO.ValoresCaracteristicas = new List<ValorCaracteristicaListadoDTO>();
            }
            List<CaracteristicaEdicionDTO> caracteristicas = ObtenerListadoCaracteristicas();
            foreach (CaracteristicaEdicionDTO caracteristica in caracteristicas)
            {
                string id = "car-" + caracteristica.Id.ToString();
                int idValor;
                try
                {
                    idValor = Convert.ToInt32(Request["itemid-" + caracteristica.Id.ToString()]);
                }
                catch
                {
                    idValor = 0;
                }
                if (Request[id] == null)
                {
                    if (caracteristica.Tipo == TipoDato.BOOLEANO)
                    {
                        wishDTO.ValoresCaracteristicas.Add(new ValorCaracteristicaListadoDTO() { Valor = "false", IdCaracteristica = caracteristica.Id, Caracteristica = caracteristica, Id = idValor });
                    }
                    else
                    {
                        wishDTO.ValoresCaracteristicas.Add(new ValorCaracteristicaListadoDTO() { Valor = "", IdCaracteristica = caracteristica.Id, Caracteristica = caracteristica, Id = idValor });
                    }
                }
                else
                {
                    if (caracteristica.Tipo == TipoDato.BOOLEANO)
                    {
                        bool boolean = Request[id].ToString() != "false";
                        wishDTO.ValoresCaracteristicas.Add(new ValorCaracteristicaListadoDTO() { Valor = boolean.ToString(), IdCaracteristica = caracteristica.Id, Caracteristica = caracteristica, Id = idValor });
                    }
                    else
                    {
                        wishDTO.ValoresCaracteristicas.Add(new ValorCaracteristicaListadoDTO() { Valor = Request[id], IdCaracteristica = caracteristica.Id, Caracteristica = caracteristica, Id = idValor });
                    }
                }
            }
            if ((ServiceFacadeFactory.Instance.EspecificacionBienFacade.Editar(wishDTO)))
            {
                return RedirectToAction("Wishlist");
            }
            ArmarListadoCaracteristicas();
            return View(wishDTO);
        }

        //
        // GET: /Wish/Delete/5

        public ActionResult Delete(int id = 0)
        {
            EspecificacionBienDTO wish = ServiceFacadeFactory.Instance.EspecificacionBienFacade.Obtener(id);
            if (wish == null)
            {
                return HttpNotFound();
            }
            return View(wish);
        }

        //
        // POST: /Wish/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ServiceFacadeFactory.Instance.EspecificacionBienFacade.Eliminar(id);
            return RedirectToAction("Wishlist");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        //
        // POST: /Wish/Wishlist
        public ActionResult Wishlist()
        {
            // Verificar
            if (Session["sitio"] != null)
            {
                SitioListadoDTO sitio = Session["sitio"] as SitioListadoDTO;
                List<EspecificacionBienListadoDTO> wishlist = ServiceFacadeFactory.Instance.EspecificacionBienFacade.Wishlist(User.Identity.Name, sitio.Id);
                return View(wishlist);
            }
            else
            {
                return View(new List<EspecificacionBienListadoDTO>());
            }
        }

        //
        // GET: /Bien/Mapa
        public ActionResult Mapa()
        {
            return View();
        }
    }
}

OL4RENT/Views/Wish/Create.cshtml
@model Ol4RentAPI.DTO.EspecificacionBienAltaDTO

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="float-right">
    <div>
        <!-- Mapa -->
        @Html.Partial("../Wish/Mapa")
    </div>
</div>

<h2>Crear Wish</h2>

@using (Html.BeginForm("Create", "Wish", FormMethod.Post,new { name = "RegisterForm", id = "RegisterForm", encType = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    
        
    <fieldset>
        <legend>EspecificacionBien</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Titulo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Titulo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Rango)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Rango)
        </div>

       <div>
           @Html.HiddenFor(model => model.Latitud)
           @Html.HiddenFor(model => model.Longitud)
           @Html.Hidden("click", ((bool)ViewBag.Click).ToString())
       </div>
        <ol>
        @foreach (Ol4RentAPI.DTO.CaracteristicaEdicionDTO caracteristica in ViewBag.Caracteristicas)
            {
            <li>
                @Html.Label("car-" + caracteristica.Id.ToString(), caracteristica.Nombre)
                @if (caracteristica.Tipo == Ol4RentAPI.Model.TipoDato.BOOLEANO)
                {
                    @Html.CheckBox("car-" + caracteristica.Id.ToString(),false);
                }
                else if (caracteristica.Tipo == Ol4RentAPI.Model.TipoDato.FECHA)
                {
                    @Html.TextBox("car-" + caracteristica.Id.ToString());
                    <script type="text/javascript">
                        $(document).ready(function () {
                            $("#car-@caracteristica.Id.ToString()").datepicker
                                ({
                                    dateFormat: 'dd/mm/yy',
                                    showStatus: true,
                                    showWeeks: true,
                                    highlightWeek: true,
                                    numberOfMonths: 1,
                                    showAnim: "scale",
                                    showOptions: {
                                        origin: ["top", "left"]
                                    }
                                });
                        });
                    </script>
                }
                else if (caracteristica.Tipo == Ol4RentAPI.Model.TipoDato.HORA)
                {
                    @Html.TextBox("car-" + caracteristica.Id.ToString(), String.Format("{0: HH:mm}", DateTime.Now), DateTime.Now.ToString("HH:mm"));
                    <!--<span class="timeEntry_control" style="display: inline-block; background-image: url(/Images/spinnerDefault.png); width: 20px; height: 20px; background-position: 0px 0px; background-repeat: no-repeat no-repeat;" title="Previous field"></span>-->
                    <script type="text/javascript">
                        $(document).ready(function () { $('#car-@caracteristica.Id.ToString()').timeEntry({ show24Hours: true }); });
                    </script>
                }
                else if (caracteristica.Tipo == Ol4RentAPI.Model.TipoDato.ENTERO)
                {
                    @Html.TextBox("car-" + caracteristica.Id.ToString(), 0, "0");
                }
                else if (caracteristica.Tipo == Ol4RentAPI.Model.TipoDato.DECIMAL)
                {
                    @Html.TextBox("car-" + caracteristica.Id.ToString(), 0, "0,0");
                }
                else
                {
                    @Html.TextBox("car-" + caracteristica.Id.ToString());
                }
            </li>
            }
            </ol>
        <p>
            <input type="submit" value="Crear" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Volver a Wishlist", "Wishlist")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/crearWish.js")
    @Scripts.Render("~/Scripts/jquery-ui-1.8.20.js")
    @Scripts.Render("~/Scripts/jquery.timepicker.js")
    @Scripts.Render("~/Scripts/jquery.timepicker.timeentry.js")
}

OL4RENT/Views/Wish/Delete.cshtml
@model Ol4RentAPI.DTO.EspecificacionBienDTO

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="float-right">
    <div>
        <!-- Mapa -->
        <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAR_JcEyolVGeSAWZsQ4g8cIuOLBnDD2l4&sensor=false"></script>
        <script type="text/javascript">
            var map;
            function initialize() {

                var mapOptions = {
                    center: new google.maps.LatLng(-34.887057, -56.171036),
                    panControl: true,
                    zoomControl: true,
                    mapTypeControl: true,
                    scaleControl: true,
                    streetViewControl: true,
                    overviewMapControl: true,
                    zoom: 12,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
                google.maps.Map.prototype.marker = new google.maps.Marker();

                crearPunto();
            }
            google.maps.event.addDomListener(window, 'load', initialize);

            function crearPunto() {
                var lat = $("#Latitud").val().toString().replace(",", ".");
                var lng = $("#Longitud").val().toString().replace(",", ".");
                var location = new google.maps.LatLng(lat, lng);
                gLocation = location;
                google.maps.Map.prototype.marker.setMap(null);

                var marker = new google.maps.Marker({
                    position: location,
                    map: map
                });

                google.maps.Map.prototype.marker = marker;
                map.setCenter(location);
                crearCirculo();
            }

            var gLocation = new google.maps.LatLng(-34.887057, -56.171036);
            function crearCirculo() {
                var circulo = new google.maps.Circle({
                    strokeColor: '#FF0000',
                    strokeOpacity: 0.8,
                    strokeWeight: 2,
                    fillColor: '#FF0000',
                    fillOpacity: 0.35,
                    map: map,
                    center: gLocation,
                    radius: $("#Rango").val() == "" ? 1 : parseInt($("#Rango").val())
                });
            }

        </script>
        <h3>Ubicación</h3>
        <br />
        <div id="map-canvas" style="width: 450px; height: 300px"></div>
    </div>
</div>

<h2>Borrar</h2>

<h3>¿Quieres borrar el wish?</h3>
<fieldset>
    <legend>Wish</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Titulo):
         @Html.DisplayFor(model => model.Titulo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Rango):
         @Html.DisplayFor(model => model.Rango)
    </div>
    <div>
        @Html.HiddenFor(model => model.Latitud)
        @Html.HiddenFor(model => model.Longitud)
        @Html.HiddenFor(model => model.Rango)

    </div>
    <ol>
        @if (Model.ValoresCaracteristicas != null && Model.ValoresCaracteristicas.Count() > 0){
            foreach (Ol4RentAPI.DTO.ValorCaracteristicaListadoDTO item in Model.ValoresCaracteristicas)
            {
            <li>
                @Html.DisplayName(item.Caracteristica.Nombre):
                @if (item.Caracteristica.Tipo == Ol4RentAPI.Model.TipoDato.BOOLEANO)
                {
                    if (item.Valor.AsBool())
                    {
                        @Html.DisplayName("Si")
                    }else
                    {
                        @Html.DisplayName("No")
                    }
                }else
                {
                    @Html.DisplayName(item.Valor)
                }
            </li>
            
            }
        }
    </ol>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Borrar" /> |
        @Html.ActionLink("Volver a Wishlist", "Wishlist")
    </p>
}

OL4RENT/Views/Wish/Details.cshtml
@model Ol4RentAPI.DTO.EspecificacionBienDTO

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="float-right">
    <div>
        <!-- Mapa -->
        <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAR_JcEyolVGeSAWZsQ4g8cIuOLBnDD2l4&sensor=false"></script>
        <script type="text/javascript">
            var map;
            function initialize() {

                var mapOptions = {
                    center: new google.maps.LatLng(-34.887057, -56.171036),
                    panControl: true,
                    zoomControl: true,
                    mapTypeControl: true,
                    scaleControl: true,
                    streetViewControl: true,
                    overviewMapControl: true,
                    zoom: 12,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
                google.maps.Map.prototype.marker = new google.maps.Marker();

                crearPunto();
            }
            google.maps.event.addDomListener(window, 'load', initialize);

            function crearPunto() {
                var lat = $("#Latitud").val().toString().replace(",", ".");
                var lng = $("#Longitud").val().toString().replace(",", ".");
                var location = new google.maps.LatLng(lat, lng);
                gLocation = location;
                google.maps.Map.prototype.marker.setMap(null);

                var marker = new google.maps.Marker({
                    position: location,
                    map: map
                });

                google.maps.Map.prototype.marker = marker;
                map.setCenter(location);
                crearCirculo();
            }

            var gLocation = new google.maps.LatLng(-34.887057, -56.171036);
            function crearCirculo() {
                var circulo = new google.maps.Circle({
                    strokeColor: '#FF0000',
                    strokeOpacity: 0.8,
                    strokeWeight: 2,
                    fillColor: '#FF0000',
                    fillOpacity: 0.35,
                    map: map,
                    center: gLocation,
                    radius: $("#Rango").val() == "" ? 1 : parseInt($("#Rango").val())
                });
            }

        </script>
        <h3>Ubicación</h3>
        <br />
        <div id="map-canvas" style="width: 450px; height: 300px"></div>
    </div>
</div>

<h2>Detalles</h2>

<fieldset>
    <legend>Wish</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Titulo):
         @Html.DisplayFor(model => model.Titulo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Rango):
         @Html.DisplayFor(model => model.Rango)
    </div>
    <div>
        @Html.HiddenFor(model => model.Latitud)
        @Html.HiddenFor(model => model.Longitud)
        @Html.HiddenFor(model => model.Rango)

    </div>
    <ol>
        @if (Model.ValoresCaracteristicas != null && Model.ValoresCaracteristicas.Count() > 0){
            foreach (Ol4RentAPI.DTO.ValorCaracteristicaListadoDTO item in Model.ValoresCaracteristicas)
            {
            <li>
                @Html.DisplayName(item.Caracteristica.Nombre):
                @if (item.Caracteristica.Tipo == Ol4RentAPI.Model.TipoDato.BOOLEANO)
                {
                    if (item.Valor.AsBool())
                    {
                        @Html.DisplayName("Si")
                    }else
                    {
                        @Html.DisplayName("No")
                    }
                }else
                {
                    @Html.DisplayName(item.Valor)
                }
            </li>
            
            }
        }
    </ol>
</fieldset>
<p>
    @Html.ActionLink("Editar", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Borrar", "Delete", new { id=Model.Id }) |
    @Html.ActionLink("Volver a Wishlist", "Wishlist") 
</p>

OL4RENT/Views/Wish/Edit.cshtml
@model Ol4RentAPI.DTO.EspecificacionBienDTO

@{
    ViewBag.Title = "Edit";
}

<div class="float-right">
    <div>
        <!-- Mapa -->
        <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAR_JcEyolVGeSAWZsQ4g8cIuOLBnDD2l4&sensor=false"></script>
        <script type="text/javascript">
            var map;
            function initialize() {

                var mapOptions = {
                    center: new google.maps.LatLng(-34.887057, -56.171036),
                    panControl: true,
                    zoomControl: true,
                    mapTypeControl: true,
                    scaleControl: true,
                    streetViewControl: true,
                    overviewMapControl: true,
                    zoom: 12,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
                google.maps.Map.prototype.marker = new google.maps.Marker();

                google.maps.event.addListener(map, "click", function (event) { esperaClick(event.latLng); });

                CrearPunto();
            }
            google.maps.event.addDomListener(window, 'load', initialize);

            function CrearPunto() {
                var lat = $("#Latitud").val().toString().replace(",", ".");
                var lng = $("#Longitud").val().toString().replace(",", ".");
                var location = new google.maps.LatLng(lat, lng);
                gLocation = location;
                google.maps.Map.prototype.marker.setMap(null);

                var marker = new google.maps.Marker({
                    position: location,
                    map: map
                });

                google.maps.Map.prototype.marker = marker;
                map.setCenter(location);
                crearCirculo();
            }

            var gLocation = new google.maps.LatLng(-34.887057, -56.171036);

            function esperaClick(location) {
                gLocation = location;
                google.maps.Map.prototype.marker.setMap(null);

                var marker = new google.maps.Marker({
                    position: location,
                    map: map
                });

                google.maps.Map.prototype.marker = marker;
                map.setCenter(location);
                var lat = location.lat().toString().replace(".", ",");
                var lng = location.lng().toString().replace(".", ",");
                $("#Latitud").val(lat);
                $("#Longitud").val(lng);
                crearCirculo();
            }
            var circulo = new google.maps.Circle();
            function crearCirculo() {
                circulo.setMap(null);
                circulo = new google.maps.Circle({
                    strokeColor: '#FF0000',
                    strokeOpacity: 0.8,
                    strokeWeight: 2,
                    fillColor: '#FF0000',
                    fillOpacity: 0.35,
                    map: map,
                    center: gLocation,
                    radius: $("#Rango").val() == "" ? 1 : parseInt($("#Rango").val())
                });
            }

        </script>
        <h3>Ubicación</h3>
        <br />
        <div id="map-canvas" style="width: 450px; height: 300px"></div>
    </div>
</div>

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Wish</legend>

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Latitud)
        @Html.HiddenFor(model => model.Longitud)

        <div class="editor-label">
            @Html.LabelFor(model => model.Titulo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Titulo)
            @Html.ValidationMessageFor(model => model.Titulo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Rango)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Rango)
            @Html.ValidationMessageFor(model => model.Rango)
        </div>

        <ol >
            @if (Model.ValoresCaracteristicas != null && Model.ValoresCaracteristicas.Count() > 0)
            {
                foreach (Ol4RentAPI.DTO.ValorCaracteristicaListadoDTO item in Model.ValoresCaracteristicas)
                {
                <li >
                    @Html.Hidden("itemid-" + item.Caracteristica.Id.ToString(), item.Id.ToString())
                    @Html.Label("car-" + item.Caracteristica.Id.ToString(), item.Caracteristica.Nombre)
                    @if (item.Caracteristica.Tipo == Ol4RentAPI.Model.TipoDato.BOOLEANO)
                    {
                        @Html.CheckBox("car-" + item.Caracteristica.Id.ToString(), item.Valor.AsBool());
                    }
                    else if (item.Caracteristica.Tipo == Ol4RentAPI.Model.TipoDato.FECHA)
                    {
                        @Html.TextBox("car-" + item.Caracteristica.Id.ToString(), item.Valor);
                        <script type="text/javascript">
                            $(document).ready(function () {
                                $("#car-@item.Caracteristica.Id.ToString()").datepicker
                                        ({
                                            dateFormat: 'dd/mm/yy',
                                            showStatus: true,
                                            showWeeks: true,
                                            highlightWeek: true,
                                            numberOfMonths: 1,
                                            showAnim: "scale",
                                            showOptions: {
                                                origin: ["top", "left"]
                                            }
                                        });
                                });
                        </script>
                    }
                    else if (item.Caracteristica.Tipo == Ol4RentAPI.Model.TipoDato.HORA)
                    {
                        @Html.TextBox("car-" + item.Caracteristica.Id.ToString(), String.Format("{0: HH:mm}", DateTime.Now), item.Valor);
                        <script type="text/javascript">
                            $(document).ready(function () { $('#car-@item.Caracteristica.Id.ToString()').timeEntry({ show24Hours: true }); });
                        </script>
                    }
                    else if (item.Caracteristica.Tipo == Ol4RentAPI.Model.TipoDato.ENTERO)
                    {
                        @Html.TextBox("car-" + item.Caracteristica.Id.ToString(), 0, item.Valor);
                    }
                    else if (item.Caracteristica.Tipo == Ol4RentAPI.Model.TipoDato.DECIMAL)
                    {
                        @Html.TextBox("car-" + item.Caracteristica.Id.ToString(), 0, item.Valor);
                    }
                    else
                    {
                        @Html.TextBox("car-" + item.Caracteristica.Id.ToString(), item.Valor);
                    }
                    </li>
                }
            }
        </ol>

        <p>
            <input type="submit" value="Guardar" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Volver a Wishlist", "Wishlist")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/crearWish.js")
    @Scripts.Render("~/Scripts/jquery-ui-1.8.20.js")
    @Scripts.Render("~/Scripts/jquery.timepicker.js")
    @Scripts.Render("~/Scripts/jquery.timepicker.timeentry.js")
}

OL4RENT/Views/Wish/Index.cshtml
@model IEnumerable<Ol4RentAPI.Model.EspecificacionBien>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Latitud)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Longitud)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rango)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Latitud)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Longitud)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rango)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

OL4RENT/Views/Wish/Wishlist.cshtml
@model IEnumerable<Ol4RentAPI.DTO.EspecificacionBienListadoDTO>
@{
    ViewBag.Title = "Wishlist";
}
<div>
    @Html.ActionLink("Nuevo Wish", "Create", "Wish")
</div>
<h2>Mi Wishlist</h2>
<ul>
@foreach (var item in Model) {
    <li>
        <div>
            @Html.ActionLink(item.Titulo, "Details", "Wish", new { id=item.Id }, null)
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.Id }) |
            @Html.ActionLink("Borrar", "Delete", new { id=item.Id })
        </div>
    </li>
}
</ul>
<div>
    @Html.ActionLink("Principal", "Index","Home")
</div>