OL4RENTBackOffice/Controllers/ReporteController.cs
using GoogleChartSharp;
using Ol4RentAPI.DTO;
using Ol4RentAPI.Facades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OL4RENTBackOffice.Controllers
{
    public class ReporteController : Controller
    {
        //
        // GET: /Reporte/
        [Authorize(Roles = "SITE_ADMIN")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "SITE_ADMIN")]
        public ActionResult ContenidosInadecuadosPorSitio()
        {
            ArmarComboSitios(null);
            return View(new List<ContenidoDTO>());
        }

        [Authorize(Roles = "SITE_ADMIN")]
        [HttpPost]
        public ActionResult ContenidosInadecuadosPorSitio(int idSitio)
        {
            ArmarComboSitios(idSitio);
            List<ContenidoDTO> contenidos = ServiceFacadeFactory.Instance.BienFacade.ContenidosInadecuadosPorSitio(idSitio);
            return View(contenidos);
        }

        [Authorize(Roles = "SITE_ADMIN")]
        public ActionResult RegistroDeBienesEnTiempo()
        {
            ArmarFiltroFechas(null, null);
            ArmarComboSitios(null);
            return View(new RegistroBienDTO() { Tipo = "", Valores = new List<ValorRegistroBienDTO>() });
        }

        [Authorize(Roles = "SITE_ADMIN")]
        [HttpPost]
        public ActionResult RegistroDeBienesEnTiempo(int idSitio, DateTime fechaInicio, DateTime fechaFin)
        {
            ArmarFiltroFechas(fechaInicio, fechaFin);
            ArmarComboSitios(idSitio);
            RegistroBienDTO reporte = ServiceFacadeFactory.Instance.BienFacade.RegistroDeBienesEnTiempo(idSitio, fechaInicio, fechaFin);
            ArmarGraficaRegistroDeBienesEnTiempo(reporte);
            return View(reporte);
        }

        private void ArmarFiltroFechas(DateTime? fechaInicio, DateTime? fechaFin)
        {
            ViewBag.FechaInicio = fechaInicio.HasValue ? fechaInicio.Value : DateTime.Now.AddMonths(-1);
            ViewBag.FechaFin = fechaFin.HasValue ? fechaFin.Value : DateTime.Now;
        }

        private void ArmarComboSitios(int? idSitio)
        {
            List<SitioListadoDTO> sitios = ServiceFacadeFactory.Instance.SitioFacade.ObtenerPorUsuario(User.Identity.Name);
            List<SelectListItem> comboSitios = sitios.Select(s => new SelectListItem() { Selected = idSitio.HasValue ? idSitio.Value == s.Id : false, Text = s.Nombre, Value = s.Id.ToString() }).ToList();
            ViewBag.Sitios = comboSitios;
        }

        private void ArmarGraficaRegistroDeBienesEnTiempo(RegistroBienDTO registro)
        {
            if (registro.Valores.Count() > 0)
            {
                int maximo = registro.Valores.Select(v => v.Cantidad).Max();
                int[] eje = new int[maximo + 1];
                for (int i = 0; i <= maximo; i++)
                {
                    eje[i] = i;
                }
                //LineChart chart = new LineChart(200, 150, LineChartType.SingleDataSet);
                BarChart chart = new BarChart(200, 150, BarChartOrientation.Vertical, BarChartStyle.Stacked);
                chart.AddAxis(new ChartAxis(ChartAxisType.Left, eje.Select(i => i.ToString()).ToArray()) { FontSize = 10 });
                chart.AddAxis(new ChartAxis(ChartAxisType.Bottom, registro.Valores.Select(val => val.Etiqueta).ToArray()) { FontSize = 10 });
                chart.SetData(registro.Valores.Select(val => Convert.ToSingle(val.Cantidad * 100 / maximo)).ToArray());
                string url = chart.GetUrl();
                ViewBag.ChartUrl = url;
            }
        }
    }
}

OL4RENTBackOffice/Views/Shared/Menu.cshtml
@if (Request.IsAuthenticated) {
<nav>
    <ul id="menu">
        @if (User.IsInRole(Ol4RentAPI.Model.RolEnum.SUPER_ADMIN.ToString()) || User.IsInRole(Ol4RentAPI.Model.RolEnum.SITE_ADMIN.ToString()))
        {
        <li>@Html.ActionLink("Sitios", "Listar", "Sitio")</li>
        }
        @if (User.IsInRole(Ol4RentAPI.Model.RolEnum.SUPER_ADMIN.ToString())) {
        <li>@Html.ActionLink("Orígenes de Datos", "Listar", "OrigenDatos")</li>
        }
        @if (User.IsInRole(Ol4RentAPI.Model.RolEnum.SITE_ADMIN.ToString())) {
        <li>@Html.ActionLink("Reportes", "Index", "Reporte")</li>
        }
    </ul>
</nav>
}

OL4RENTBackOffice/Views/Shared/_Layout.Android.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - OL4RENT - BackOffice</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" /
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title"><a href="@Url.Action("Index", "Home")"><img src="~/Images/logo.png" alt="OL4RENT" /></a></p>
                </div>

                <div class="header">
                    <label style="font-size: 25px; color: #7F7F7F; text-align: center">
                        <b>EDICIÓN ANDROID</B>
                    </label>
                </div>

                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    @Html.Partial("Menu")
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - OL4RENT - BackOffice - Edición Android</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

OL4RENTBackOffice/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - OL4RENT - BackOffice</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" /
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title"><a href="@Url.Action("Index", "Home")"><img src="~/Images/logo.png" alt="OL4RENT" /></a></p>
                </div>

                <div class="header">
                    <label style="font-size: 25px; color: #7F7F7F; text-align: center">
                        <b>EDICIÓN MOBILE</B>
                    </label>
                </div>

                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    @Html.Partial("Menu")
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - OL4RENT - BackOffice - Edición Mobile</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

OL4RENTBackOffice/Views/Shared/_Layout.WindowsPhone.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - OL4RENT - BackOffice</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" /
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title"><a href="@Url.Action("Index", "Home")"><img src="~/Images/logo.png" alt="OL4RENT" /></a></p>
                </div>

                <div class="header">
                    <label style="font-size: 25px; color: #7F7F7F; text-align: center">
                        <b>EDICIÓN WINDOWS PHONE</B>
                    </label>
                </div>

                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    @Html.Partial("Menu")
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - OL4RENT - BackOffice - Edición Windows Phone</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

OL4RENTBackOffice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - OL4RENT - BackOffice</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" /
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title"><a href="@Url.Action("Index", "Home")"><img src="~/Images/logo.png" alt="OL4RENT" /></a></p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    @Html.Partial("Menu")
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - OL4RENT - BackOffice</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

OL4RENTBackOffice/Views/Shared/_Layout.iPhone.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - OL4RENT - BackOffice</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" /
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title"><a href="@Url.Action("Index", "Home")"><img src="~/Images/logo.png" alt="OL4RENT" /></a></p>
                </div>

                <div class="header">
                    <label style="font-size: 25px; color: #7F7F7F; text-align: center">
                        <b>EDICIÓN IPHONE</B>
                    </label>
                </div>

                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    @Html.Partial("Menu")
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - OL4RENT - BackOffice - Edición IPhone</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

OL4RENTBackOffice/Views/Shared/_LoginFormMinPartial.cshtml
@model Ol4RentAPI.Model.LoginModel
<section id="loginMin">
@using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post)) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Inicio de sesión</legend>
        <ol>
            <li>
                @Html.ValidationMessageFor(m => m.NombreUsuario)
                @Html.ValidationMessageFor(m => m.Contraseña)
            </li>
        </ol>
        @Html.Label("NombreUsuario", "Usuario:")
        @Html.TextBoxFor(m => m.NombreUsuario)
        @Html.Label("Contraseña", "Contraseña:")
        @Html.PasswordFor(m => m.Contraseña)
        @Html.CheckBoxFor(m => m.RememberMe)
        @Html.LabelFor(m => m.RememberMe, new { @class = "checkbox" })
        <input type="submit" value="Iniciar sesión" />
    </fieldset>
}
@Html.Action("ExternalLoginsList", "Account", new { ReturnUrl = ViewBag.ReturnUrl })
</section>

OL4RENTBackOffice/Views/Shared/_LoginFormPartial.cshtml
@model Ol4RentAPI.Model.LoginModel
<h4>Utilice su cuenta local para inciar sesión.</h4>
@using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Inicio de sesión</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.NombreUsuario)
                @Html.TextBoxFor(m => m.NombreUsuario)
                @Html.ValidationMessageFor(m => m.NombreUsuario)
            </li>
            <li>
                @Html.LabelFor(m => m.Contraseña)
                @Html.PasswordFor(m => m.Contraseña)
                @Html.ValidationMessageFor(m => m.Contraseña)
            </li>
            <li>
                @Html.CheckBoxFor(m => m.RememberMe)
                @Html.LabelFor(m => m.RememberMe, new { @class = "checkbox" })
            </li>
        </ol>
        <input type="submit" value="Iniciar sesión" />
    </fieldset>
}
<h4>O utilice una cuenta externa.</h4>
<p>
    @Html.Action("ExternalLoginsList", "Account", new { ReturnUrl = ViewBag.ReturnUrl })
</p>